//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDAnalyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDDAnalyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method in an aggregate must return void or self on the same aggregate.
        /// </summary>
        internal static string AggregateMethodMustReturnVoidOrSelfDescription {
            get {
                return ResourceManager.GetString("AggregateMethodMustReturnVoidOrSelfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method  &apos;{0}&apos; in &apos;{1}&apos; must return void or self on the same aggregate.
        /// </summary>
        internal static string AggregateMethodMustReturnVoidOrSelfMessageFormat {
            get {
                return ResourceManager.GetString("AggregateMethodMustReturnVoidOrSelfMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method in an aggregate must return void or self.
        /// </summary>
        internal static string AggregateMethodMustReturnVoidOrSelfTitle {
            get {
                return ResourceManager.GetString("AggregateMethodMustReturnVoidOrSelfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties in an aggregate cannot be public.
        /// </summary>
        internal static string PropertiesCannotBePublicDescription {
            get {
                return ResourceManager.GetString("PropertiesCannotBePublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; in &apos;{1}&apos; cannot not be public.
        /// </summary>
        internal static string PropertiesCannotBePublicMessageFormat {
            get {
                return ResourceManager.GetString("PropertiesCannotBePublicMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties in an aggregate cannot be public.
        /// </summary>
        internal static string PropertiesCannotBePublicTitle {
            get {
                return ResourceManager.GetString("PropertiesCannotBePublicTitle", resourceCulture);
            }
        }
    }
}
